### ISSUE TITLE
Analyze the UPF Text Mining Framework when cleaning a document

### ISSUE THREAD

**Issue by cbadenes** [oeg-upm/epnoi#46]
14:14:29.154 [PARSER] [hread-5] WARN  o.e.p.a.u.AnnotatedDocument - Error when cleaning document: edu.upf.taln.dri.lib.model.DocumentImpl@2deea99f
java.lang.NullPointerException: null
    at edu.upf.taln.dri.lib.model.DocumentImpl.cleanUp(DocumentImpl.java:1988) ~[lib-1.2.jar:na]
    at org.epnoi.parser.annotator.upf.AnnotatedDocument.clean(AnnotatedDocument.java:182) ~[AnnotatedDocument.class:na]
    at org.epnoi.parser.service.ParserService.parse(ParserService.java:132) [ParserService.class:na]
    at org.epnoi.parser.eventbus.FileCreatedEventHandler.handle(FileCreatedEventHandler.java:31) [FileCreatedEventHandler.class:na]
    at org.epnoi.eventbus.rabbitmq.RabbitMQClient$2.handleDelivery(RabbitMQClient.java:157) [epnoi-eventbus-0.2-SNAPSHOT.jar:na]
    at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144) [amqp-client-3.5.6.jar:na]
    at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99) [amqp-client-3.5.6.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by cbadenes** [comment]
It has been handled from the harvester
