### ISSUE TITLE
Virtuoso transaction aborted due to a database checkpoint or database-wide atomic operation

### ISSUE THREAD

**Issue by cbadenes** [oeg-upm/epnoi#71]
``` txt
7:23:08.730 [LEARNER-LEGACY] [duler-1] WARN  o.e.l.s.LearnerTask - Unexpected error trying to learn terms and relations from domain: Domain(super=Resource(super=LinkableElement(uri=http://drinventor.eu/domains/7df34748-7fad-486e-a799-3bcd86a03499, creationTime=2016-02-29T12:29+0100)), name=siggraph, description=from-test-junit)
com.hp.hpl.jena.shared.JenaException: Convert results are FAILED.:virtuoso.jdbc4.VirtuosoException: SR325: Transaction aborted due to a database checkpoint or database-wide atomic operation. Please retry transaction
    at virtuoso.jena.driver.VirtuosoQueryExecution.execDescribe(VirtuosoQueryExecution.java:229) ~[jena-virtuoso-1.0.jar:na]
    at virtuoso.jena.driver.VirtuosoQueryExecution.execDescribe(VirtuosoQueryExecution.java:203) ~[jena-virtuoso-1.0.jar:na]
    at org.epnoi.uia.informationstore.dao.rdf.PaperRDFDAO.remove(PaperRDFDAO.java:72) ~[epnoi-legacy-storage-0.2-SNAPSHOT.jar:na]
    at org.epnoi.uia.informationstore.VirtuosoInformationStore.remove(VirtuosoInformationStore.java:74) ~[epnoi-legacy-storage-0.2-SNAPSHOT.jar:na]
    at org.epnoi.informationhandler.wrappers.PaperWrapper.remove(PaperWrapper.java:77) ~[epnoi-legacy-wrappers-0.2-SNAPSHOT.jar:na]
    at org.epnoi.uia.informationhandler.InformationHandlerImpl.remove(InformationHandlerImpl.java:152) ~[epnoi-legacy-core-0.2-SNAPSHOT.jar:na]
    at org.epnoi.learner.filesystem.DemoDataLoader._removeComputerGraphicsCorpus(DemoDataLoader.java:114) ~[DemoDataLoader.class:na]
    at org.epnoi.learner.filesystem.DemoDataLoader.erase(DemoDataLoader.java:49) ~[DemoDataLoader.class:na]
    at org.epnoi.learner.service.LearnerTask.loadData(LearnerTask.java:82) ~[LearnerTask.class:na]
    at org.epnoi.learner.service.LearnerTask.run(LearnerTask.java:60) ~[LearnerTask.class:na]
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.9.RELEASE.jar:4.1.9.RELEASE]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by cbadenes** [comment]
Implemented a retry policy
